---
language: python

before_install:
  - pip install poetry

install:
  - poetry install

script:
  - python -m pytest --cov=invoice tests/
  - python -m mypy invoice/
  - black --check  invoice/ tests/
  - flake8 cmdbox
